spring:
  config:
    activate:
      on-profile: local
  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 30
  server:
    servlet:
      session:
        cookie:
          secure: true
          same-site: none
          http-only: true
          name: JSESSIONID
